code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension adelphes.android-dev-ext
code --install-extension alefragnani.numbered-bookmarks
code --install-extension alexcvzz.vscode-sqlite
code --install-extension AntonyDalmiere.android-support
code --install-extension bradlc.vscode-tailwindcss
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CodeSandbox-io.codesandbox-projects
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension foxundermoon.shell-format
code --install-extension fwcd.kotlin
code --install-extension johnpapa.pwa-tools
code --install-extension josetr.cmake-language-support-vscode
code --install-extension JuanBlanco.solidity
code --install-extension keyhr.42-c-format
code --install-extension mathiasfrohlich.Kotlin
code --install-extension mikestead.dotenv
code --install-extension mongodb.mongodb-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension NomicFoundation.hardhat-solidity
code --install-extension pmndrs.pmndrs
code --install-extension polypus74.trusty-rusty-snippets
code --install-extension pranaygp.vscode-css-peek
code --install-extension Prisma.prisma
code --install-extension RamiroBerrelleza.bitbucket-pull-requests
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension sashaweiss.block-travel
code --install-extension silvenon.mdx
code --install-extension SimonSiefke.svg-preview
code --install-extension styled-components.vscode-styled-components
code --install-extension svelte.svelte-vscode
code --install-extension toba.vsfire
code --install-extension trufflesuite-csi.truffle-vscode
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vsls-contrib.gistfs
code --install-extension WallabyJs.console-ninja
code --install-extension WallabyJs.quokka-vscode
code --install-extension wix.glean
code --install-extension wix.vscode-import-cost
code --install-extension Zignd.html-css-class-completion
