#!/bin/bash
wi () {
	_help () {
		echo "Help:
====
  You can get help this help by either of below commands:
  $ wi
  $ wi -h
  $ wi --help

Usage:
======
  You can use wi with any commands like wget, tar or more.
  $ wi wget
  $ wi tar

Bypass cache
============
  By providing - in the end of the command
  $ wi wget -
"
}
	if [ -z $1 ] || [ $1 = "-h" ] || [ $1 = "--help" ]; then
		_help
		return
	fi

	#DEBUG: (NOT USING THIS ANYWHERE THOUGH):
	# [ "${USER:0:1}" = "a" ]; echo $?
	# we are checking that value starts with a above.

	if ! [ -d /tmp/wi ]; then
		# Remove if its a file coz -d checks only if its a directory.
		rm -f /tmp/wi 
		mkdir /tmp/wi
	fi

	# DEBUGGING:
	# Usage: `wi tar -`
	# [ "$2" = "-" ] && echo provided a dash..

	# Use cache if file already exists but skip if second argument is `-` (to force refetch):
	if [ -f "/tmp/wi/$1.txt" ] && [ "$2" != "-" ]; then
		echo "->>> USING CACHE"
		echo "================"
		cat /tmp/wi/$1.txt
	else
		echo ">>> FETCHING FRESH <<<"
		echo "======================"
	
		URL="https://raw.githubusercontent.com/sahilrajput03/sahilrajput03/master/wi"
		wget --quiet "$URL/$1.txt" -O "/tmp/wi/$1.txt" && cat "/tmp/wi/$1.txt"

		# LEARN wget
		# --quiet
		# -nv means no-verbose bcoz default is verbose on.
		# --debug to show debugging via wget
		# -O means overwrite existing file if already present bcoz by default it append incremental number to the output file name if the file is already present.
	fi
}
